### ISSUE TITLE
preserving permissions: Function not implemented

### ISSUE THREAD

**Issue by ssche** [relan/exfat#9] opened 2015-10-22 00:24 UTC
I hope this is the right place for posting this.

I am using iPython which writes data on a portable USB drive which is exFat formatted (under CentOS 7). iPython uses `shutil.copy2()` which in turn [should work similar to `cp -r` preserving file metadata](https://docs.python.org/2/library/shutil.html#shutil.copy2). The problem is that calling this function (or `cp -r`) raises an exception. Is there any way of configuring the exfat driver to silently ignore the fact that it doesn't handle metadata?

I've tried to reproduce the problem with the latest master version. If you try `cp -r file1 file2` on the exFat drive, you should be able to get this error message:

```
cp: preserving permissions for ‘file2’: Function not implemented
```

**Comment by ssche** [comment] 2015-10-22 00:37
I just tried to disable [this check](https://github.com/relan/exfat/blob/b7953e251b0aec68cdd056ddafd2d4c17b338b8b/fuse/main.c#L316) and it "resolves" the issue. I'm not sure about possible side-effects though...

**Comment by relan** [comment] 2015-10-22 04:47
I cannot reproduce this issue on my Fedora 22 box, `cp -r file1 file2` does not produce any errors for me. What OS/distro do you use? Also please post `mount | grep exfat` to see what mount options are used.

**Comment by ssche** [comment] 2015-10-22 06:07
`CentOS Linux release 7.1.1503 (Core)`. `mount | grep exfat` doesn't return anything (perhaps that's the problem).

I tried: `mount | grep fuse` instead which returned:
```
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
/dev/sdc1 on /run/media/drive type fuseblk (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096)
```

**Comment by relan** [comment] 2015-10-22 09:38
`cp -r file1 file2` works fine for me on `CentOS Linux release 7.1.1503 (Core)`. Are you sure that you are using the latest version? Please check the output of `mount.exfat-fuse -V` (it should say 1.2.1 if you built it from the latest master). Since switch from SCons to autotools the binaries can be installed into a different directory, so check that you have exactly one copy of `mount.exfat-fuse` in your system.

**Comment by ssche** [comment] 2015-10-22 23:04
I can check next week.

**Comment by relan** [comment] 2016-04-27 17:20
No reply in 6 months, closing. Feel free to reopen if you have any new info.

**Closed by relan** 2016-04-27 17:20 UTC
Labels: bug, fuse
