### ISSUE TITLE
mkexfatfs -i claims to be setting the volume id. it doesn't.

### ISSUE THREAD

**Issue by mhellwig** [relan/exfat#127] opened 2019-07-10 23:17 UTC
the volume id turns out to be some other random 32-digit hex number, not the one I set. Tried setting it with dashes and without - doesn't work. Please at least don't claim in the manpage that it does .. Gave me false hope for an hour.

**Comment by relan** [comment] 2019-07-11 04:40
Could you show the exact command you used?

**Comment by mhellwig** [comment] 2019-07-11 07:48
sure
`mkexfatfs -i <32 digits of hex goes here> -n XXXX-XXXX /dev/mmcblk0p1`

where the XXXXes are also numbers. The command runs successfully and returns no error. The card is formatted. The label (XXXX-XXXX) is set correctly but the ID (the 32 hex digits) is NOT set to what I defined on the commandline, it's some completely unrelated other 32 hex digits.

**Comment by relan** [comment] 2019-07-11 08:57
-i sets exFAT-specific, 4-byte (32-bit) ID.

You probably want to set GPT partition ID (32 hex digits constitute a 16-byte (128-bit) ID). If so, you should use a partition editor for that, e.g. parted.

**Comment by mhellwig** [comment] 2019-07-11 09:07
huh. ok, so I misunderstood what it was doing. So apparently what Android uses to determine the mountpoint is the partition ID? I'll investigate ...

**Comment by relan** [comment] 2020-05-04 10:49
Closing as there's nothing to do here.

**Closed by relan** 2020-05-04 10:49 UTC

**Comment by drrossum** [comment] 2020-06-25 18:52
I'm running into the same issue. I don't have a GPT on the sdcard that I could set UUIDs for. What is the solution?

**Comment by drrossum** [comment] 2020-06-25 18:55
From looking at the code I see the issue is that it does not discriminate a user-provided value of 00000000 from "undefined".
