### ISSUE TITLE
v1.2.4, missing files with optional entries

### ISSUE THREAD

**Issue by jiamn** [relan/exfat#48] opened 2016-11-21 00:52 UTC
I have a SONY SXS 32G card writed by sony video camera. 
My machine is win7 64bit, ubuntu 14.04.1 LTS 32bit and exfat-fuse 1.2.4.
The card in sony card speed reader US30, I found 15 files in \XDROOT\Clip by win7,
C:\Users\hp>dir g:\xdroot\clip
 驱动器 G 中的卷没有标签。   ** no label
 卷的序列号是 446B-09C9      

 g:\xdroot\clip 的目录

2014/03/11  01:14    <DIR>          .
2014/03/11  01:14    <DIR>          ..
2014/03/11  01:16       180,334,128 966_0001.MXF
2014/03/11  01:16         1,847,296 966_0001R01.BIM
2014/03/11  01:17        95,263,280 966_0002.MXF
2014/03/11  01:16             2,520 966_0001M01.XML
2014/03/11  01:17         2,338,816 966_0002R01.BIM
2014/03/11  01:18       100,910,652 966_0003.MXF
2014/03/11  01:17             2,243 966_0002M01.XML
2014/03/11  01:18         2,093,056 966_0003R01.BIM
2014/03/11  01:18        92,534,332 966_0004.MXF
2014/03/11  01:18             2,520 966_0003M01.XML
2014/03/11  01:18         1,921,024 966_0004R01.BIM
2014/03/11  01:20        55,682,560 966_0005.MXF
2014/03/11  01:18             2,520 966_0004M01.XML
2014/03/11  01:20         2,166,784 966_0005R01.BIM
2014/03/11  01:20             2,227 966_0005M01.XML
              15 个文件    535,103,958 字节
               2 个目录 31,393,841,152 可用字节

but I mount the card to ubuntu 14.04.1, the files number in same dir changes to 10.

root@usbweb:/# ls /mnt/XDROOT/Clip/ -lai
total 14848
 4 drwxrwxrwx 1 root root  524288  3月 11  2014 .
 2 drwxrwxrwx 1 root root  524288  3月 11  2014 ..
 6 -rwxrwxrwx 1 root root    2520  3月 11  2014 966_0001M01.XML
 5 -rwxrwxrwx 1 root root 1847296  3月 11  2014 966_0001R01.BIM
 8 -rwxrwxrwx 1 root root    2243  3月 11  2014 966_0002M01.XML
 7 -rwxrwxrwx 1 root root 2338816  3月 11  2014 966_0002R01.BIM
10 -rwxrwxrwx 1 root root    2520  3月 11  2014 966_0003M01.XML
 9 -rwxrwxrwx 1 root root 2093056  3月 11  2014 966_0003R01.BIM
12 -rwxrwxrwx 1 root root    2520  3月 11  2014 966_0004M01.XML
11 -rwxrwxrwx 1 root root 1921024  3月 11  2014 966_0004R01.BIM
14 -rwxrwxrwx 1 root root    2227  3月 11  2014 966_0005M01.XML
13 -rwxrwxrwx 1 root root 2166784  3月 11  2014 966_0005R01.BIM

missing MXF file with video content, I can use them in win7.

root@usbweb:/home/sc/exfat/fsck# exfatfsck /dev/sdb1
exfatfsck 1.2.4
Checking file system on /dev/sdb1.
File system version           1.0
Sector size                   2 KB
Cluster size                512 KB
Volume size                  30 GB
Used space                  606 MB
Available space              29 GB
WARN: unknown entry type 0xe1.
WARN: unknown entry type 0xe1.
WARN: unknown entry type 0xe1.
WARN: unknown entry type 0xe1.
WARN: unknown entry type 0xe1.
Totally 10 directories and 13 files.
File system checking finished. No errors found.

**Comment by relan** [comment] 2016-11-21 05:59
Looks like a duplicate of #42.

Could you apply the following patch (to the `develop` branch) and post the output of `exfatfsck` after that?
```patch
diff --git a/fsck/main.c b/fsck/main.c
index cda1965..c1c6f94 100644
--- a/fsck/main.c
+++ b/fsck/main.c
@@ -26,7 +26,7 @@
 #include <inttypes.h>
 #include <unistd.h>
 
-#define exfat_debug(format, ...)
+// #define exfat_debug(format, ...)
 
 uint64_t files_count, directories_count;
 
diff --git a/libexfat/node.c b/libexfat/node.c
index 3f49fb2..9f8426d 100644
--- a/libexfat/node.c
+++ b/libexfat/node.c
@@ -286,6 +286,16 @@ static int readdir(struct exfat* ef, const struct exfat_node* parent,
 		}
 
 		entry = get_entry_ptr(ef, it);
+		if (entry->type)
+			exfat_debug("entry %08x %08x %08x %08x %08x %08x %08x %08x",
+					exfat_bswap32(((uint32_t*) entry)[0]),
+					exfat_bswap32(((uint32_t*) entry)[1]),
+					exfat_bswap32(((uint32_t*) entry)[2]),
+					exfat_bswap32(((uint32_t*) entry)[3]),
+					exfat_bswap32(((uint32_t*) entry)[4]),
+					exfat_bswap32(((uint32_t*) entry)[5]),
+					exfat_bswap32(((uint32_t*) entry)[6]),
+					exfat_bswap32(((uint32_t*) entry)[7]));
 		switch (entry->type)
 		{
 		case EXFAT_ENTRY_FILE:
```

This patch logs raw directory entries.

**Comment by jiamn** [comment] 2016-11-21 07:18
I am not sure whether you need diff with two main.c, so I  post 
root@usbweb:/home/sc/relandp/exfat-develop/fsck# git diff  /home/sc/exfat/fsck/main.c /home/sc/relandp/exfat-develop/fsck/main.c 
diff --git a/home/sc/exfat/fsck/main.c b/home/sc/relandp/exfat-develop/fsck/main.c
index a72d74c..cda1965 100644
--- a/home/sc/exfat/fsck/main.c
+++ b/home/sc/relandp/exfat-develop/fsck/main.c
@@ -33,7 +33,7 @@ uint64_t files_count, directories_count;
 static int nodeck(struct exfat* ef, struct exfat_node* node)
 {
        const cluster_t cluster_size = CLUSTER_SIZE(*ef->sb);
-       cluster_t clusters = (node->size + cluster_size - 1) / cluster_size;
+       cluster_t clusters = DIV_ROUND_UP(node->size, cluster_size);
        cluster_t c = node->start_cluster;
        int rc = 0;
 
download and configure and make ,make install

root@usbweb:/home/sc/relandp/exfat-develop/fsck# exfatfsck /dev/sdb1
exfatfsck 1.2.4
Checking file system on /dev/sdb1.
File system version           1.0
Sector size                   2 KB
Cluster size                512 KB
Volume size                  30 GB
Used space                  606 MB
Available space              29 GB
WARN: unknown entry type 0xe1.
WARN: unknown entry type 0xe1.
WARN: unknown entry type 0xe1.
WARN: unknown entry type 0xe1.
WARN: unknown entry type 0xe1.
Totally 10 directories and 13 files.
File system checking finished. No errors found.

**Comment by jiamn** [comment] 2016-11-21 23:40
sorry  first time with github

**Comment by relan** [comment] 2016-11-22 06:52
I need to see those 0xe1 entries to figure out the problem. Please clone the repository:

    git clone https://github.com/relan/exfat.git
    cd exfat

Switch to the `issue48` branch (I've added debug logging there):

    git checkout issue48

Compile (no need to install):

    autoreconf --install
    ./configure
    make

Check the volume and post here the full output:

    fsck/exfatfsck /dev/sdb1

**Comment by jiamn** [comment] 2016-11-22 07:30
root@usbweb:/home/sc/exfat# fsck/exfatfsck /dev/sdb1
exfatfsck 1.2.4
DEBUG: 83000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000.
DEBUG: 81000000 00000000 00000000 00000000 00000000 22000000 c41d0000 00000000.
DEBUG: 82000000 0dd319e6 00000000 00000000 00000000 23000000 cc160000 00000000.
DEBUG: 85022af7 10000000 c9096b44 c9096b44 c9096b44 6464a0a0 a0000000 00000000.
DEBUG: c0010006 37290000 00000800 00000000 00000000 25000000 00000800 00000000.
DEBUG: c1005800 44005200 4f004f00 54000000 00000000 00000000 00000000 00000000.
Checking file system on /dev/sdb1.
File system version           1.0
Sector size                   2 KB
Cluster size                512 KB
Volume size                  30 GB
Used space                  606 MB
Available space              29 GB
DEBUG: /XDROOT: fragmented, 524288 bytes, cluster 37.
DEBUG: 8502be53 10000000 c9096b44 c9096b44 c9096b44 6464a0a0 a0000000 00000000.
DEBUG: c0010004 2e900000 00000800 00000000 00000000 26000000 00000800 00000000.
DEBUG: c1005400 61006b00 65000000 00000000 00000000 00000000 00000000 00000000.
DEBUG: 8502f647 10000000 c9096b44 c9096b44 c9096b44 6464a0a0 a0000000 00000000.
DEBUG: c0010004 34060000 00000800 00000000 00000000 27000000 00000800 00000000.
DEBUG: c1004300 6c006900 70000000 00000000 00000000 00000000 00000000 00000000.
DEBUG: 8502e571 10000000 c9096b44 c9096b44 c9096b44 6464a0a0 a0000000 00000000.
DEBUG: c0010003 2e380000 00000800 00000000 00000000 28000000 00000800 00000000.
DEBUG: c1005300 75006200 00000000 00000000 00000000 00000000 00000000 00000000.
DEBUG: 85028bf4 10000000 c9096b44 c9096b44 c9096b44 6464a0a0 a0000000 00000000.
DEBUG: c0010007 096c0000 00000800 00000000 00000000 09000000 00000800 00000000.
DEBUG: c1004700 65006e00 65007200 61006c00 00000000 00000000 00000000 00000000.
DEBUG: 8502867c 10000000 c9096b44 c9096b44 c9096b44 6464a0a0 a0000000 00000000.
DEBUG: c0010004 35ca0000 00000800 00000000 00000000 0a000000 00000800 00000000.
DEBUG: c1004500 64006900 74000000 00000000 00000000 00000000 00000000 00000000.
DEBUG: 8502ef4e 10000000 c9096b44 c9096b44 c9096b44 6464a0a0 a0000000 00000000.
DEBUG: c0010006 b2980000 00000800 00000000 00000000 0b000000 00000800 00000000.
DEBUG: c1005400 68006d00 62006e00 6c000000 00000000 00000000 00000000 00000000.
DEBUG: 850270b4 10000000 c9096b44 c9096b44 c9096b44 6464a0a0 a0000000 00000000.
DEBUG: c0010008 0fc50000 00000800 00000000 00000000 0c000000 00000800 00000000.
DEBUG: c1005500 73006500 72004400 61007400 61000000 00000000 00000000 00000000.
DEBUG: 8502ac7f 20000000 c9096b44 960a6b44 960a6b44 6464a0a0 a0000000 00000000.
DEBUG: c0010009 c6710000 24010000 00000000 00000000 e7020000 24010000 00000000.
DEBUG: c1004300 55004500 55005000 2e005800 4d004c00 00000000 00000000 00000000.
DEBUG: 850205db 20000000 c9096b44 c9096b44 c9096b44 6464a0a0 a0000000 00000000.
DEBUG: c001000c 239a0000 1e010000 00000000 00000000 42000000 1e010000 00000000.
DEBUG: c1004400 49005300 43004d00 45005400 41002e00 58004d00 4c000000 00000000.
DEBUG: 850263c2 20000000 c9096b44 960a6b44 960a6b44 6464a0a0 a0000000 00000000.
DEBUG: c001000c 24b30000 88090000 00000000 00000000 e6020000 88090000 00000000.
DEBUG: c1004d00 45004400 49004100 50005200 4f002e00 58004d00 4c000000 00000000.
DEBUG: 050257dc 20000000 8f0a6b44 900a6b44 900a6b44 6400a0a0 a0000000 00000000.
DEBUG: 4001000c 7d6b0000 00500000 00000000 00000000 62000000 00500000 00000000.
DEBUG: 41005f00 53004c00 56004700 30003000 32002e00 53004c00 56000000 00000000.
DEBUG: 0502372c 20000000 8f0a6b44 900a6b44 900a6b44 6400a0a0 a0000000 00000000.
DEBUG: 4001000c fd6a0000 00780000 00000000 00000000 63000000 00780000 00000000.
DEBUG: 41005f00 53004c00 56004700 30003000 31002e00 53004c00 56000000 00000000.
DEBUG: /XDROOT/Take: fragmented, 524288 bytes, cluster 38.
DEBUG: /XDROOT/Clip: fragmented, 524288 bytes, cluster 39.
DEBUG: 85039081 20000000 090a6b44 0f0a6b44 0f0a6b44 6464a0a0 a0000000 00000000.
DEBUG: c001000c c9460000 30aebf0a 00000000 00000000 82020000 30aebf0a 00000000.
DEBUG: c1003900 36003600 5f003000 30003000 31002e00 4d005800 46000000 00000000.
DEBUG: e1018f8f 97155d78 75419a61 0c4288c9 5cba0000 21010000 00006000 00000000.
WARN: unknown entry type 0xe1.
DEBUG: 4101000c c9760000 00006000 00000000 00000000 21010000 00006000 00000000.
DEBUG: 41003900 36003600 5f003000 30003000 31002e00 53004c00 49000000 00000000.
DEBUG: 8502b429 20000000 090a6b44 0f0a6b44 0f0a6b44 6464a0a0 a0000000 00000000.
DEBUG: c001000f 4c8f0000 00301c00 00000000 00000000 84020000 00301c00 00000000.
DEBUG: c1003900 36003600 5f003000 30003000 31005200 30003100 2e004200 49004d00.
DEBUG: 8503c1b0 20000000 1d0a6b44 270a6b44 270a6b44 6400a0a0 a0000000 00000000.
DEBUG: c001000c 49470000 309aad05 00000000 00000000 c2110000 309aad05 00000000.
DEBUG: c1003900 36003600 5f003000 30003000 32002e00 4d005800 46000000 00000000.
DEBUG: e1018f8f 97155d78 75419a61 0c4288c9 5cba0000 21110000 00003000 00000000.
WARN: unknown entry type 0xe1.
DEBUG: 4101000c 49770000 00003000 00000000 00000000 21110000 00003000 00000000.
DEBUG: 41003900 36003600 5f003000 30003000 32002e00 53004c00 49000000 00000000.
DEBUG: 8502cd34 20000000 0f0a6b44 0f0a6b44 0f0a6b44 6464a0a0 a0000000 00000000.
DEBUG: c001000f 253f0000 d8090000 00000000 00000000 85020000 d8090000 00000000.
DEBUG: c1003900 36003600 5f003000 30003000 31004d00 30003100 2e005800 4d004c00.
DEBUG: 8502edb4 20000000 1d0a6b44 270a6b44 270a6b44 6400a0a0 a0000000 00000000.
DEBUG: c001000f 4e8f0000 00b02300 00000000 00000000 c4110000 00b02300 00000000.
DEBUG: c1003900 36003600 5f003000 30003000 32005200 30003100 2e004200 49004d00.
DEBUG: 8503ff7b 20000000 400a6b44 470a6b44 470a6b44 6464a0a0 a0000000 00000000.
DEBUG: c001000c c9470000 3cc60306 00000000 00000000 e2210000 3cc60306 00000000.
DEBUG: c1003900 36003600 5f003000 30003000 33002e00 4d005800 46000000 00000000.
DEBUG: e1018f8f 97155d78 75419a61 0c4288c9 5cba0000 21210000 00003800 00000000.
WARN: unknown entry type 0xe1.
DEBUG: 4101000c c9770000 00003800 00000000 00000000 21210000 00003800 00000000.
DEBUG: 41003900 36003600 5f003000 30003000 33002e00 53004c00 49000000 00000000.
DEBUG: 850281ef 20000000 270a6b44 270a6b44 270a6b44 0000a0a0 a0000000 00000000.
DEBUG: c001000f 273f0000 c3080000 00000000 00000000 c5110000 c3080000 00000000.
DEBUG: c1003900 36003600 5f003000 30003000 32004d00 30003100 2e005800 4d004c00.
DEBUG: 850275c3 20000000 400a6b44 470a6b44 470a6b44 6400a0a0 a0000000 00000000.
DEBUG: c001000f 508f0000 00f01f00 00000000 00000000 e4210000 00f01f00 00000000.
DEBUG: c1003900 36003600 5f003000 30003000 33005200 30003100 2e004200 49004d00.
DEBUG: 850370db 20000000 520a6b44 590a6b44 590a6b44 6400a0a0 a0000000 00000000.
DEBUG: c001000c 49480000 3cf68305 00000000 00000000 c2310000 3cf68305 00000000.
DEBUG: c1003900 36003600 5f003000 30003000 34002e00 4d005800 46000000 00000000.
DEBUG: e1018f8f 97155d78 75419a61 0c4288c9 5cba0000 21310000 00003000 00000000.
WARN: unknown entry type 0xe1.
DEBUG: 4101000c 49780000 00003000 00000000 00000000 21310000 00003000 00000000.
DEBUG: 41003900 36003600 5f003000 30003000 34002e00 53004c00 49000000 00000000.
DEBUG: 85020894 20000000 470a6b44 470a6b44 470a6b44 0000a0a0 a0000000 00000000.
DEBUG: c001000f 293f0000 d8090000 00000000 00000000 e5210000 d8090000 00000000.
DEBUG: c1003900 36003600 5f003000 30003000 33004d00 30003100 2e005800 4d004c00.
DEBUG: 85029907 20000000 520a6b44 590a6b44 590a6b44 6400a0a0 a0000000 00000000.
DEBUG: c001000f 528f0000 00501d00 00000000 00000000 c4310000 00501d00 00000000.
DEBUG: c1003900 36003600 5f003000 30003000 34005200 30003100 2e004200 49004d00.
DEBUG: 8503edca 20000000 8f0a6b44 960a6b44 960a6b44 6464a0a0 a0000000 00000000.
DEBUG: c001000c c9480000 00a65103 00000000 00000000 e2020000 00a65103 00000000.
DEBUG: c1003900 36003600 5f003000 30003000 35002e00 4d005800 46000000 00000000.
DEBUG: e1018f8f 97155d78 75419a61 0c4288c9 5cba0000 a1000000 00002000 00000000.
WARN: unknown entry type 0xe1.
DEBUG: 4101000c c9780000 00002000 00000000 00000000 a1000000 00002000 00000000.
DEBUG: 41003900 36003600 5f003000 30003000 35002e00 53004c00 49000000 00000000.
DEBUG: 8502f102 20000000 580a6b44 590a6b44 590a6b44 6400a0a0 a0000000 00000000.
DEBUG: c001000f 2b3f0000 d8090000 00000000 00000000 c5310000 d8090000 00000000.
DEBUG: c1003900 36003600 5f003000 30003000 34004d00 30003100 2e005800 4d004c00.
DEBUG: 8502db73 20000000 8f0a6b44 960a6b44 960a6b44 6464a0a0 a0000000 00000000.
DEBUG: c001000f 548f0000 00102100 00000000 00000000 e4020000 00102100 00000000.
DEBUG: c1003900 36003600 5f003000 30003000 35005200 30003100 2e004200 49004d00.
DEBUG: 050266db 20000000 8f0a6b44 960a6b44 960a6b44 6464a0a0 a0000000 00000000.
DEBUG: 4001000c d0d00000 0000007a 00000000 00000000 02030000 0000007a 00000000.
DEBUG: 41003900 36003600 5f003000 30003000 35002e00 52005300 56000000 00000000.
DEBUG: 8502f494 20000000 960a6b44 960a6b44 960a6b44 6464a0a0 a0000000 00000000.
DEBUG: c001000f 2d3f0000 b3080000 00000000 00000000 e5020000 b3080000 00000000.
DEBUG: c1003900 36003600 5f003000 30003000 35004d00 30003100 2e005800 4d004c00.
DEBUG: /XDROOT/Clip/966_0001R01.BIM: fragmented, 1847296 bytes, cluster 644.
DEBUG: /XDROOT/Clip/966_0001M01.XML: fragmented, 2520 bytes, cluster 645.
DEBUG: /XDROOT/Clip/966_0002R01.BIM: fragmented, 2338816 bytes, cluster 4548.
DEBUG: /XDROOT/Clip/966_0002M01.XML: fragmented, 2243 bytes, cluster 4549.
DEBUG: /XDROOT/Clip/966_0003R01.BIM: fragmented, 2093056 bytes, cluster 8676.
DEBUG: /XDROOT/Clip/966_0003M01.XML: fragmented, 2520 bytes, cluster 8677.
DEBUG: /XDROOT/Clip/966_0004R01.BIM: fragmented, 1921024 bytes, cluster 12740.
DEBUG: /XDROOT/Clip/966_0004M01.XML: fragmented, 2520 bytes, cluster 12741.
DEBUG: /XDROOT/Clip/966_0005R01.BIM: fragmented, 2166784 bytes, cluster 740.
DEBUG: /XDROOT/Clip/966_0005M01.XML: fragmented, 2227 bytes, cluster 741.
DEBUG: /XDROOT/Sub: fragmented, 524288 bytes, cluster 40.
DEBUG: /XDROOT/General: fragmented, 524288 bytes, cluster 9.
DEBUG: 8502d883 10000000 ca096b44 ca096b44 ca096b44 0000a0a0 a0000000 00000000.
DEBUG: c0010004 395e0000 00000800 00000000 00000000 c2000000 00000800 00000000.
DEBUG: c1005300 6f006e00 79000000 00000000 00000000 00000000 00000000 00000000.
DEBUG: /XDROOT/General/Sony: fragmented, 524288 bytes, cluster 194.
DEBUG: 8502b61e 10000000 ca096b44 ca096b44 ca096b44 6464a0a0 a0000000 00000000.
DEBUG: c0010008 50560000 00000800 00000000 00000000 c3000000 00000800 00000000.
DEBUG: c1005000 6c006100 6e006e00 69006e00 67000000 00000000 00000000 00000000.
DEBUG: /XDROOT/General/Sony/Planning: fragmented, 524288 bytes, cluster 195.
DEBUG: /XDROOT/Edit: fragmented, 524288 bytes, cluster 10.
DEBUG: /XDROOT/Thmbnl: fragmented, 524288 bytes, cluster 11.
DEBUG: /XDROOT/UserData: fragmented, 524288 bytes, cluster 12.
DEBUG: /XDROOT/CUEUP.XML: fragmented, 292 bytes, cluster 743.
DEBUG: /XDROOT/DISCMETA.XML: fragmented, 286 bytes, cluster 66.
DEBUG: /XDROOT/MEDIAPRO.XML: fragmented, 2440 bytes, cluster 742.
Totally 10 directories and 13 files.
File system checking finished. No errors found.

**Comment by relan** [comment] 2016-11-23 07:11
Thanks for the log!

I still don't understand where Windows gets those *.MXF files entries from. The 0xe1 entries don't look like anything useful and there are no file name entries. Could you share a full FS dump?

1. Backup the data from you memory card.
2. Erase memory card (will take some time):
    `dd if=/dev/zero of=/dev/sdb1 bs=1M`
3. Insert memory card into your Sony camera.
4. Format it into exFAT.
5. Take a short video.
6. Insert memory card into your PC.
7. Create a compressed dump (will take some time):
    `gzip -c /dev/sdb1 > sony-exfat.img.gz`
8. Share `sony-exfat.img.gz` file.

**Comment by jiamn** [comment] 2016-11-23 08:32
ok, I will share file serveral days later.
How share file?

**Comment by relan** [comment] 2016-11-23 14:47
Step 2 erases to whole SD card as a block device, it has nothing to do with FS. Note that after this all SD card content will be lost! This step is required due to privacy reasons (otherwise it will be possible to read files that were on the card before) and to reduce dump size (zeros are compressed very well).

You can use any file sharing service, the dump should be only a couple of megabytes.

**Comment by jiamn** [comment] 2016-11-24 00:02
write 0 to card success!
wait few days, the camera is with my friend.

**Comment by jiamn** [comment] 2016-11-30 00:39
http://pan.baidu.com/s/1dEM0ShF
code：a3un
If any question, leave message, or email:16013889@qq.com

**Comment by relan** [comment] 2016-11-30 17:01
Thanks for the dump. I need some time to analyze it.

**Comment by jiamn** [comment] 2016-12-01 00:07
Thank you.

**Comment by relan** [comment] 2016-12-01 09:25
The dump contains two (!) exFAT file systems (each with a single FAT). No idea how this works. I suspect this has something to do with a partition table. Could you please upload dump of the whole device:

    gzip -c /dev/sdb > sony-exfat-full.img.gz

It will include partition table and will have almost the same size as the previous dump.

**Comment by jiamn** [comment] 2016-12-02 07:17
http://pan.baidu.com/s/1nvuaEQP 
code：d85s

**Comment by relan** [comment] 2016-12-02 14:52
Downloaded, thanks! Will check it out soon.

**Comment by relan** [comment] 2016-12-04 07:51
I've the reason of the problem. After all there is a bug in finalizing optional entries handling (0xe1): node structure is simply lost in this case. Unfortunately the fix will require a lot of work becuse everywhere in the code I assume that a complex file entry consists of meta1, meta2 and name entries. This is wrong: possible optional entries should be taken into account too. I've already fixed directory reading, but I'll also need to refactor node flushing and renaming.

**Comment by jiamn** [comment] 2016-12-04 12:45
I think  the exfat structure most writed by large-fast-mem-card manufacter like SONY,whether  maybe many new type entry used by them.
Thank lots for your work.

**Comment by relan** [comment] 2016-12-05 19:05
Since fixing this issue will require a lot of changes, I decided to release v1.2.5 with all the other fixes to date and devote v1.2.6 to this bug.

**Comment by jiamn** [comment] 2016-12-08 12:51
I am Chinese, my English is urgly, Best wishes to you  All the best

**Comment by relan** [comment] 2016-12-20 06:53
A short update: I'm currently doing a big refactoring. It's needed to implement proper handling of optional entries. The new code is highly experimental, will push it when it's polished enough.

I decided to switch from low-level `exfat_pread`/`exfat_pwrite` functions to higher level `exfat_generic_pread`/`exfat_generic_pwrite` functions for working with directories content. This is a huge change, but in the end it should simplify code and improve performance due to multiple IO operations merging.

**Comment by relan** [comment] 2017-01-10 07:18
I've finished the big refactoring.

@jiamn, could you test the code in the `issue48` branch please? It now handles optional entries properly, so your Sony memory card should just work.

**Comment by jiamn** [comment] 2017-01-10 07:31
root@usbweb:/home/sc/exfat# fsck/exfatfsck /dev/sdb1
exfatfsck 1.2.5
Checking file system on /dev/sdb1.
File system version           1.0
Sector size                   2 KB
Cluster size                512 KB
Volume size                  30 GB
Used space                  373 MB
Available space              29 GB
Totally 10 directories and 6 files.
File system checking finished. No errors found.

**Comment by jiamn** [comment] 2017-01-10 08:25
sorry, I can't see the missing file  *.mxf.

root@usbweb:/home/sc# mount.exfat /dev/sdb1 /mnt
FUSE exfat 1.2.4
WARN: '/dev/sdb1' is write-protected, mounting read-only.
root@usbweb:/home/sc# ls /mnt/XDROOT/Clip/
966_0001M01.XML  966_0001R01.BIM
root@usbweb:/home/sc# fsck/exfatfsck /dev/sdb1
bash: fsck/exfatfsck: No such file or directory
root@usbweb:/home/sc# fsck/exfatfsck /dev/sdb1
bash: fsck/exfatfsck: No such file or directory
root@usbweb:/home/sc# cd exfat
root@usbweb:/home/sc/exfat# git checkout issue48
Already on 'issue48'
Your branch is up-to-date with 'origin/issue48'.
root@usbweb:/home/sc/exfat# fsck/exfatfsck /dev/sdb1
exfatfsck 1.2.5
Checking file system on /dev/sdb1.
File system version           1.0
Sector size                   2 KB
Cluster size                512 KB
Volume size                  30 GB
Used space                  373 MB
Available space              29 GB
Totally 10 directories and 6 files.
File system checking finished. No errors found.

Any wrong in procedure?

**Comment by relan** [comment] 2017-01-10 08:30
> I can't see the missing file *.mxf.

> FUSE exfat 1.2.4

You are trying an old version of fuse-exfat. Try the one that you've just compiled and installed into /usr/sbin.

**Comment by jiamn** [comment] 2017-01-10 08:38
root@usbweb:/usr/sbin# mount.exfat --version
FUSE exfat 1.2.4
mount.exfat: invalid option -- '-'
Usage: mount.exfat [-d] [-o options] [-V] <device> <dir>
root@usbweb:/usr/sbin# mount.exfat /dev/sdb1 /mnt
FUSE exfat 1.2.4
WARN: '/dev/sdb1' is write-protected, mounting read-only.
root@usbweb:/usr/sbin# ls /mnt/XDROOT/Clip/
966_0001M01.XML  966_0001R01.BIM
root@usbweb:/usr/sbin# 

Any wrong?

**Comment by relan** [comment] 2017-01-10 09:14
Unlike DOS/Windows, Unix shell does not look for an executable in the current directory. If you want to run a program from the current directory, you need to specify it explicitly, e.g. `./mount.exfat`. Or just use absolute path (i.e. `/usr/sbin/mount.exfat`).

**Comment by jiamn** [comment] 2017-01-10 09:46
root@usbweb:/usr/sbin# ./mount.exfat --version
FUSE exfat 1.2.5
./mount.exfat: invalid option -- '-'
Usage: ./mount.exfat [-d] [-o options] [-V] <device> <dir>
root@usbweb:/usr/sbin# umount /mnt
root@usbweb:/usr/sbin# ./mount.exfat /dev/sdb1 /mnt
FUSE exfat 1.2.5
WARN: '/dev/sdb1' is write-protected, mounting read-only.
root@usbweb:/usr/sbin# ls /mnt/XDROOT/Clip/
966_0001M01.XML  966_0001R01.BIM
root@usbweb:/usr/sbin# umount /mnt
root@usbweb:/usr/sbin# /usr/sbin/mount.exfat /dev/sdb1 /mnt
FUSE exfat 1.2.5
WARN: '/dev/sdb1' is write-protected, mounting read-only.
root@usbweb:/usr/sbin# ls /mnt/XDROOT/Clip/
966_0001M01.XML  966_0001R01.BIM

**Comment by jiamn** [comment] 2017-01-10 10:47
I use clean machine without exfat mount, install issue48 and make as your direction.
It works, 

root@sc-desktop:/home/sc/exfat# mkdir /tempmnt
root@sc-desktop:/home/sc/exfat# mount.exfat /dev/sdb1 /tempmnt
FUSE exfat 1.2.5
WARN: '/dev/sdb1' is write-protected, mounting read-only.
root@sc-desktop:/home/sc/exfat# ls /tempmnt/XDROOT/Clip/ -l
total 296960
-rwxrwxrwx 1 root root      2520  3月 24  2014 966_0001M01.XML
-rwxrwxrwx 1 root root 297157180  3月 24  2014 966_0001.MXF
-rwxrwxrwx 1 root root   6111232  3月 24  2014 966_0001R01.BIM

Thank you.
Maybe more mount version in that machine.
Waiting normal version 1.2.6.

**Comment by relan** [comment] 2017-01-10 15:58
Great! Thanks for testing.

You can uninstall source-built version using

    sudo make uninstall

> Maybe more mount version in that machine.

Note that mount.exfat is usually a symlink to mount.exfat-fuse.

> Waiting normal version 1.2.6.

It'll take some time to prepare a new release because I need to run some tests.

**Comment by relan** [comment] 2017-01-28 19:26
Fixed in v1.2.6.

**Closed by relan** 2017-01-28 19:26 UTC
Labels: bug, fuse

**Comment by jiamn** [comment] 2017-01-28 23:45
It's spring holiday in China.
Happy new year to you.

**Comment by relan** [comment] 2017-01-29 05:51
In Russia we celebrate New Year on 1 Jan (and then Old New Year on 14 Jan). Many people call each year after a zodiac animal, thus 2017 is the year of Rooster. No idea why, probably Chinese cultural influence. :)

Happy New Year!
