### ISSUE TITLE
Please at least add an option to update checksums anyway in exfatfsck

### ISSUE THREAD

**Issue by ytrezq** [relan/exfat#54] opened 2017-03-09 02:34 UTC
Hello, would it be technically possible to implement an option to update the vbr checksum anyway in exfatfsck *(it’s not about correcting errors, but just letting exfatfuse and other tools from other projects go while knowing risks)*

    ERROR: invalid VBR checksum 0x459076eb (expected 0xd7d66df4).
If I understand things correctly, the vbr checksum‘s value is part of the data being checksummed, isn’t it ?

**Comment by relan** [comment] 2017-03-09 17:57
> would it be technically possible to implement an option to update the vbr checksum anyway in exfatfsck (it’s not about correcting errors, but just letting exfatfuse and other tools from other projects go while knowing risks)

Of course it's technically possible (though quite dangerous). But why is this better than teaching `exfatfsck` to fix errors?

> vbr checksum‘s value is part of the data being checksummed, isn’t it ?

VBR checksum itself is not checksummed.

**Comment by ytrezq** [comment] 2017-03-09 21:27
@relan :`VBR checksum itself is not checksummed.` Ok, so it’s impossible for the vbr checksum to start at the first byte of a device partition ?

    But why is this better than teaching  exfatfsck  to fix errors?
Currently, I need to test other implementations, and so far your tool seems to be the only open source one running in userspace.
So this is only for testing purpose, I have no data to rescue on an exfat volume.

**Comment by relan** [comment] 2017-03-10 04:48
> so it’s impossible for the vbr checksum to start at the first byte of a device partition ?

At the 1st byte of partition starts VBR. VBR checksum is located in 11th sector from the beginning of the partition. See `verify_vbr_checksum()` function. For testing you can just remove the check there.

**Comment by ytrezq** [comment] 2017-03-10 05:17
@relan : `VBR checksum is located in 11th sector from the beginning of the partition`ok, so it mean there’s a bug in the filesystem implementation I tested, I definitely need a tool to update checksums, please !

**Comment by relan** [comment] 2017-03-10 06:49
Well, yesterday I've actually implemented VBR checksum repair in `exfatfsck` just to estimate how hard and ugly this would be. Check out `repair` branch.

**Comment by ytrezq** [comment] 2017-03-10 06:53
@relan : thanks, would it possible to get the same thing for node checksums ?

Of course, I only want to update checksums, not to modify any other things on the filesystem.

**Comment by relan** [comment] 2017-03-11 07:06
> would it possible to get the same thing for node checksums ?

Very busy right now, cannot promise anything.

I've splitted changes in the `repair` branch into 7 commits, so now it should be more obvious how to add new repair cases.

**Comment by relan** [comment] 2017-03-14 05:34
I've implemented nodes checksums repairing. See `repair` branch.

**Comment by relan** [comment] 2017-03-22 04:57
Closing as a duplicate of #3.

**Closed by relan** 2017-03-22 04:57 UTC
Labels: enhancement, utils

**Comment by Xerus2000** [comment] 2020-01-02 17:25
how can I use the functionality? On ubuntu, even after installing directly from master, I only get `exfatfsck 1.2.8`, and if I read it correctly you added this in 1.3?

**Comment by relan** [comment] 2020-01-03 06:52
> how can I use the functionality? On ubuntu, even after installing directly from master, I only get exfatfsck 1.2.8

Did you configure fuse-exfat to be installed into /usr? It installs into /usr/local by default.

**Comment by Xerus2000** [comment] 2020-01-03 11:05
ah well, it was not fuse-exfat, exfatfsck is part of exfat-utils. I now simply downloaded a `deb` from a later ubuntu version (https://packages.ubuntu.com/disco/exfat-utils) and installed it successfully :+1: 

finally I am able to change my sd-card id :P
