### ISSUE TITLE
Unable to delete any file which can be deleted on Windows

### ISSUE THREAD

**Issue by ytrezq** [relan/exfat#56] opened 2017-03-15 16:20 UTC
exfat-fuse is unable to delete the txt file located on the root directory of [this filesystem](https://cloud.githubusercontent.com/assets/3824869/23958711/44096030-09a3-11e7-8da3-9f37f1163bad.png). The fuse process exit abnormally whereas on Windows® it works just find.

You can use losetup to [mount it](https://cloud.githubusercontent.com/assets/3824869/23958711/44096030-09a3-11e7-8da3-9f37f1163bad.png) under linux or imdisk virtual disk on Windows®.

**Comment by relan** [comment] 2017-03-15 19:00
Thanks for reporting! I've reproduced this issue, give me some time to analyze it.

**Comment by ytrezq** [comment] 2017-03-16 12:28
I have other issues like this, but in order to detect them, I would need a valid filesystem as small as possible : something like less than Kb.
Of course, mkexfatfs can’t create such file system, but I see the filesystems created contains large ranges of Kb set to NULL.

**Comment by relan** [comment] 2017-03-16 18:29
So, two notes here:

1. fuse-exfat aborts when it tries to delete a file on the image you provided. This is a bug, I'll fix it.
2. The image itself contains errors. VBR says there are 12 clusters in total (clusters bitmap has appropriate size), while two files reference clusters 12 and 13, that are beyond the clusters heap.

> I would need a valid filesystem as small as possible : something like less than Kb.

Unfortunately such small exFAT images are simply impossible. Why do you need them to be so small?

**Comment by ytrezq** [comment] 2017-03-16 22:17
@relan : it would help finding more issues. And sorry I wanted to mean less than 20Kb or 30 Kb, because you know, the 72Kb mkexfatfs can create contains large range which are set to 0.
    Unfortunately such small exFAT images are simply impossible. Why do you need them to be so small?

    The image itself contains errors. VBR says there are 12 clusters in total (clusters bitmap has appropriate size), while two files reference clusters 12 and 13, that are beyond the clusters heap.
I just created the image manually, formatted it with Windows explorer, and put that data on it. Normally I didn’t something that could corrupt it.

**Comment by relan** [comment] 2017-03-17 06:28
I've pushed a new branch `robustify` that fixes this abort.

> it would help me for automatically finding more issues

How?

> I just created the image manually, formatted it with Windows explorer, and put that data on it. Normally I didn’t something that could corrupt it.

Well, you've found a bug in Windows then.

**Comment by webmaster33** [comment] 2017-03-17 07:51
It might be possible, that this Windows bug caused the problem with 
Android Dual Boot Patcher: exFAT driver issue? #52
where the sdcard was formatted under Windows 7?

**Comment by ytrezq** [comment] 2017-03-17 12:18
@relan :

    How ?
By making bit/byte flips useful. Because actually, most of the time, they happens in regions which has no influence on exfatfuse behaviour.

**Comment by relan** [comment] 2017-03-18 06:05
> It might be possible, that this Windows bug caused the problem with Android Dual Boot Patcher: exFAT driver issue?

Very unlikely. Looks like Windows' exFAT driver misbehaves when FS is extreemly small.

> By making bit/byte flips useful. Because actually, most of the time, they happens in regions which has no influence on exfatfuse behaviour.

Got it. Will see how to minimize image size.

**Comment by ytrezq** [comment] 2017-03-18 17:33
@relan : I need 2 minimal test cases, the first is as empty as possible, the second contains a normal file and directory.

**Comment by relan** [comment] 2017-03-20 07:08
> The image itself contains errors. VBR says there are 12 clusters in total (clusters bitmap has appropriate size), while two files reference clusters 12 and 13, that are beyond the clusters heap.

I was wrong. Clusters 12 and 13 are OK because clusters numbering starts from 2. So, those are the last valid clusters of the FS. I've updated `robustify` branch.

**Comment by relan** [comment] 2017-03-21 06:42
> I need 2 minimal test cases, the first is as empty as possible, the second contains a normal file and directory please.

I've made a minimal exFAT image, that's only 16 KB: [minimal.zip](https://github.com/relan/exfat/files/857258/minimal.zip). There are 2 free clusters on it, so you can create a directory and a file.

**Comment by relan** [comment] 2017-06-05 07:14
Fixed in v1.2.7.

**Closed by relan** 2017-06-05 07:14 UTC
Labels: bug, fuse
